---

- name: Install alerta dependencies
  yum:
    name: '{{ alerta_depend_pkgs }}'
    state: present

- name: Install python3 virtualenv
  pip:
    name: virtualenv
    state: present
    executable: pip3

- name: Install alerta base packages using pip
  pip:
    name: '{{ alerta_pip_packages }}'
    virtualenv: '{{ alerta_base_dir }}'
    state: present

- name: create alerta systemd service unit
  template:
    src: alerta.service.j2
    dest: /etc/systemd/system/alerta.service
    owner: root
    group: root
    mode: 0644
