- name: Create alerta web console directory
  file:
    path: '{{ alerta_web_ui_dir }}'
    state: directory

- name: download alerta web console archive
  become: false
  get_url:
    url: "{{alerta_web_console_download_url}}{{ alerta_web_console_version }}/alerta-webui.tar.gz"
    dest: "/tmp/alerta-webui.tar.gz"
    checksum: "{{ alerta_web_console_checksum | default(omit) }}"
    url_username: "{{ alerta_web_console_download_auth.username | default(omit) }}"
    url_password: "{{ alerta_web_console_download_auth.password | default(omit) }}"
    validate_certs: "{{ alerta_web_console_download_auth.validate_certs | default(True) }}"
  register: _download_archive
  until: _download_archive is succeeded
  retries: 5
  delay: 2
  run_once: true
  delegate_to: localhost
  check_mode: false
  no_log: "{{ not lookup('env', 'ANSIBLE_DEBUG') | bool }}"

- name: propagate alerta web console archive
  copy:
    src: "/tmp/alerta-webui.tar.gz"
    dest: "/tmp/alerta-webui.tgz"
    mode: 0755
    owner: "{{ alerta_web_user }}"
    group: "{{ alerta_web_user }}" 

- name: unpack alerta web console
  become: false
  unarchive:
    src: "/tmp/alerta-webui.tgz"
    dest: "{{ alerta_web_ui_dir }}"
    remote_src: true
    extra_opts: ['--strip-components=1']
    owner: "{{ alerta_web_user }}"
    group: "{{ alerta_web_user }}"
  check_mode: false

- name: Configure alerta web console
  template:
    src: config.json.j2
    dest: '{{ alerta_web_ui_dir }}/config.json'
